name: Node-Autopilot

on:
  workflow_dispatch: # 保留手动点火按钮
  schedule:
    - cron: '0 10 * * *' # 这里的 0 10 代表 UTC 10:00，即北京时间 18:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Mirror Script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nodes.txt nodes.yaml
          git commit -m "Auto Refresh Nodes (Daily 18:00)" || echo "No changes to commit"
          git push
